name: Compiler and Updater

on: [push]

jobs:
  builder:
    name: Builder for test ESP32 project
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ESP-IDF
        uses: CalinRadoni/esp-idf-v4-action@v2
        with:
          esp_idf_version: 'v4.1'

      - name: Build
        run: |
          source ~/esp/esp-idf/export.sh
          idf.py reconfigure
          idf.py app
          idf.py size
          echo "Deploying to production server on branch $GITHUB_REF"
            echo "GITHUB_SERVER_URL : $GITHUB_SERVER_URL"
            echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
            echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
            echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
            echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
            echo "RUNNER_OS: $RUNNER_OS"
            echo "Home: ${HOME}"
            echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
            echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
            echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
            echo "GITHUB_SHA: ${GITHUB_SHA}"
            echo "GITHUB_REF: ${GITHUB_REF}"
          curl -F 'file=@build/blink.bin' -F 'Version=${GITHUB_SHA}' -F 'RepositoryURL= $GITHUB_REPOSITORY' -F 'actor=${GITHUB_ACTOR}' http://68.183.56.192:3000/file/upload 
