name: learn-github-actions
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: get toolchain
        uses: docker://espressif/idf:release-v4.0
      - 
        name: building
        run: idf.py build
       
