name: learn-github-actions
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
      - uses: docker://espressif/idf:release-v4.0
        run: idf.py build
